baseURL = "https://team-ailtir.github.io/dealroom.ai/"
languageCode = "en-us"
title = "Deal Room"
theme = "hugo-book"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[params]
  BookTheme = "light"
  BookToC = true
  BookSearch = true
  BookSection = "*"
  BookRepo = "https://github.com/team-ailtir/dealroom.ai"
