baseURL = "https://username.github.io/dealroom.ai/"
languageCode = "en-us"
title = "Deal Room"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
